spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/security
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  database-platform: org.hibernate.dialect.MariaDBDialect

jwt:
  secret: PJT